<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '11.2.0',
  'acceptable_sugar_versions' => 
  array (
    0 => '11.2.0',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => '',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'entrypoint_to_get_large_tables',
  'published_date' => '2022-01-04 11:30:34',
  'type' => 'module',
  'version' => 1641295835,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'entrypoint_to_get_large_tables',
  
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/custom/Extension/application/Ext/EntryPointRegistry/entrypoint_to_get_large_tables.php',
      'to' => 'custom/Extension/application/Ext/EntryPointRegistry/entrypoint_to_get_large_tables.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/custom/entrypoint_to_get_large_tables.php',
      'to' => 'custom/entrypoint_to_get_large_tables.php',
    ),
  )
);