<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '7.11.1.0',
  'acceptable_sugar_versions' =>
		array(
					'regex_matches' => array(
						'7\\.7\\.(.*?)\\.(.*?)', // Any 7.7 Release
						'7\\.8\\.(.*?)\\.(.*?)', // Any 7.8 Release
						'7\\.9\\.(.*?)\\.(.*?)', // Any 7.9 Release
						'7\\.10\\.(.*?)\\.(.*?)', // Any 7.10 Release
						'7\\.11\\.(.*?)\\.(.*?)', // Any 7.11 Release
						'7\\.12\\.(.*?)\\.(.*?)', // Any 7.12 Release
						'8\\.0\\.(.*?)', // Any 8.0 Release
						'8\\.1\\.(.*?)' // Any 8.1 Release
					)
				),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'PRO',
    1 => 'CORP',
    2 => 'ENT',
    3 => 'ULT',
  ),
  'readme' => '',
  'key' => 'FL',
  'author' => '',
  'description' => 'Module to store email addresses for Foreign Leads',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'project_ForeignLeadsRouting',
  'published_date' => '2018-07-25 19:59:32',
  'type' => 'module',
  'version' => 1532548773,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'project_ForeignLeadsRouting',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/ForeignLeadsRouting',
      'to' => 'custom/modulebuilder/packages/ForeignLeadsRouting',
    ),
  ),
);