<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN SF1_SalesmanFinder
 */


class SF1_SalesmanFinder_sugar extends Basic {
    public $new_schema = true;
    public $module_dir = 'SF1_SalesmanFinder';
    public $object_name = 'SF1_SalesmanFinder';
    public $table_name = 'sf1_salesmanfinder';
    public $importable = true;
    public $team_id;
    public $team_set_id;
    public $team_count;
    public $team_name;
    public $team_link;
    public $team_count_link;
    public $teams;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $tag;
    public $tag_link;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $activities;
    public $following;
    public $following_link;
    public $my_favorite;
    public $favorite_link;
    public $state;
    public $metrology_coverage;
    public $metrology_email;
    public $precision_measuring_tools;
    public $precision_measuring_phone;
    public $metrology_coverage_phone;
    public $precision_measuring_email;
    public $granite;
    public $granite_phone;
    public $granite_email;
    public $precision_ground_stock;
    public $precision_ground_phone;
    public $precision_ground_email;
    public $force_measurement_systems;
    public $force_measurement_phone;
    public $force_measurement_email;
    public $regional_manager;
    public $regional_manager_phone;
    public $regional_manager_email;
    public $industrial_area;
    public $industrial_territory;
    public $country;
    public $power_tools;
    public $power_tools_phone;
    public $power_tools_email;
    public $saws;
    public $saws_phone;
    public $saws_email;
    public $saws_email_check;
    public $force_measurement_email_check;
    public $power_tools_email_check;
    public $precision_ground_email_check;
    public $pmt_email_chec;
    public $regional_manager_email_check;
    public $metrology_email_check;
    public $granite_email_check;
    
    public function bean_implements($interface){
        switch($interface){
            case 'ACL': return true;
        }
        return false;
    }
    
}